
name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload audit result
        uses: actions/upload-artifact@v3
        with:
          path: .
